# Writing Lab Reports: Style {#style}

It's easy to write a scientific report that confuses or bores the audience.  Developing a style that keeps the reader following along can be a challenge, but it is a necessary one.

This chapter contains a number of stylistic suggestions that can improve your lab reports. There isn't 'one true style' for scientific writing, but I've found that these guidelines can help when you're starting out.

## Be Concise

Parsimony is often held up as an ideal in science; if the evidence equally supports two explanations, we tend to prefer the simpler one.  The same applies to scientific writing. 

When grading previous student lab reports, I’ve noted a bad tendency to over-explain every single detail (particularly in the methods section). Avoid providing information that is unnecessary to understand the project, and don't over-describe straightforward tasks.  If you have a long repetitive section, think of a way to express the same information in a shorter space.

Here's an example from a methods section that needs to be trimmed:

> "We created imaginary lines passing through each sample point that were parallel and perpendicular to the transect and used these lines to create four quadrants.  One member of our group would carefully pace towards the closest canopy tree in each quadrant.  This was repeated by the same group member for each sapling tree.  Later, we converted our pace counts into meters by measuring the number of paces that group member took to walk ten meters.  A different group member measured the diameter at breast height (DBH) of each canopy tree by holding up a ruler to the side of the tree.  The third group member recorded the data."

The important information could be condensed into this:

> "We divided the area around each point into four quadrants, which were parallel and perpendicular to the transect. For each quadrant, we estimated the distance to the nearest canopy and sapling trees and recorded the diameter at breast height (DBH) of the canopy tree." 


The same details apply for describing calculations or analyses.  For standard or widely used procedures (such as a chi-squared test, or calculating relative abundance), you do not need to provide the formula that you used.  In general, focus on what you did:

> "We used a chi-squared test to determine whether the proportions of the five most abundant species differed between canopy and sapling trees."

not the exact procedures you used to do it

> "We created a contingency table in Excel using pivot tables by ..., then calculated the expected values by ... From this we calculated the chi-square test statistic with the formula..., determined the degrees of freedom from ..., and calculated the p-value with the Excel function...". 

A more specialized or non-standard calculation may need to be explained ("The density at a point was estimated as $N / \text{sum}(x^2)$, where N was the number of quadrants with trees and x is the distance to the tree."), but should also not be over-explained.

The same applies to the results. If you did three similar analyses to different data sets, you should try to describe the outcomes in parallel. Instead of doing this:

> "Activity significantly increased with temperature in sample 1 (r = ..., t = ..., p = ...; Figure 1).
  ... 
  Activity significantly increased with temperature in sample 2 (r = ..., t = ..., p = ...; Figure 2)
  ...
  Activity did not increase significantly in sample 3 (r = ..., t = ..., p = ...; Figure 3)."  

You should consolidate:

> "Activity significantly increased with temperature in sample 1 (r = ..., t = ..., p = ...; Figure 1A) and sample 2 (r = ..., t = ..., p = ...; Figure 1B), but not in sample 3 (r = ..., t = ..., p = ...; Figure 1C)."  

Similar advice applies to figures. 

## Sentence Structure

Your writing should flow. When moving between topics (or sub-topics), it is helpful to include transitional elements (words, phrases, or sometimes entire sentences) to help the reader follow your train of logic. This doesn't mean that you should start every few sentences in the Methods section with "Then, we [did something] ...". Some good words and phrases to use include "Following ___," "Furthermore," "However," "Alternatively," and "Yet," etc. Note that transitions aren't necessary when you are starting a new section (e.g., Methods) or labeled sub-section. 

Each sentence should serve a purpose (in terms of communicating information).  If two or more sentences are doing the same job, try to combine them (or delete one).  Conversely, sentences that are doing too much should be split.

Avoid [garden-path sentences](https://en.wikipedia.org/wiki/Garden-path_sentence) and lengthy sentences that require multiple reads to understand. 

## Passive Voice

While there are circumstances in which [passive voice](https://www.quickanddirtytips.com/education/grammar/active-voice-versus-passive-voice) is useful, it is often misused in scientific writing. Many students feel that passive voice conveys a sense of objectivity.  In many cases, it just obscures and adds unnecessary wordiness.  This is particularly common in methods and results sections.  You (in either the singular or plural sense) performed the observations or experiment; you did the calculations and analysis.  You should take credit for it. If you are worried about starting every sentence with I/we, there are other ways to restructure your writing.

For the record, I am not banning the use of passive voice.  It can be effectively used alongside active voice when appropriate.  However, I'd recommend taking a look at your passive sentences and considering if active voice would make them more straightforward.

## Word Choice

It's tempting to use longer, more technical sounding words when writing a scientific paper.  This tends to make papers harder to read with no benefit. The same is doubly true for awkward multi-word phrases that can be replaced with one, simple word. 

Two common offenders:

**Utilize**: In almost every case, **"use"** is the better choice.  "Utilize" is really only applicable for situations in which the object being used was not designed for the task to which it is being put.  Even in that situation, "use" is still preferable.  There are a few minor areas of biology where "utilize" is correct, but for now, stick to "use."

**Approximately**: use **"about."**


## Scientific and Common Names

- Latin binomials should be italicized, with genus capitalized and specific epithet in lowercase (e.g., *Ulmus crassifolia*).  
  - Only write the full scientific name the first time it appears in a section; afterwards, you can abbreviate the genus (e.g., *U. crassifolia*). At that point, stick to the abbreviation; don't switch back and forth.
  - Exception: You should never start a sentence with the abbreviated form.
- Don’t capitalize common names except for proper nouns e.g., American elm, cedar elm, Ashe's juniper, sugar hackberry.  
- The first time a species is mentioned, its scientific name should be given.  If after that you want to just use the common name, that is fine, as long as you also gave the common name the first time.  
  - E.g., first time – ‘…..cedar elm (*Ulmus crassifolia*) was found in all three habitats…..’ 
  - Later ‘….the prevalence of cedar elm could be due to….’ OR ‘….the prevalence of *U. crassifolia* could be due to….

## Other Grammar

- Put a comma after an introductory prepositional phrase.  E.g., ‘In the pasture habitat, cedar elm was...’ or ‘During the most recent drought, laurel cherry has...’
- I generally prefer Oxford commas.  While you aren’t required to use them, be consistent.
- Please only capitalize proper nouns, acronyms, and the appropriate parts of scientific names.  

## Commonly Confused Definitions

- Population and Community: 
  - A population is a collection of individuals of the same species in a particular geographic area. E.g., all the cedar elm individuals at BFL
  - A community is a collection of individuals of different species found in a particular geographic area.  E.g., all the trees found at BFL
- Random and Haphazard
  - Truly random points would be pre-selected in the lab before heading outside using a random number generator and using those randomly selected numbers as our coordinates.
  - Haphazardly selected points follow the colloquial definition of 'random.'  It's sort of like the scientific vs. common usage of the word "theory."
- Affect and effect
  - While there are [nuances and exceptions](https://www.grammarly.com/blog/affect-vs-effect/), affect is generally a verb and effect is usually noun.


## Significant Digits 

We generally aren't using high-precision instruments.  As such, you should round numbers with a large number of decimal places to an appropriate extent (Note that ecologists usually don't follow significant figures rules quite as strictly as chemists and physicists).  Generally, p-values should be rounded to four digits (and noted as < 0.0001 if they're smaller than that), while test-statistics should probably have no more than two decimal places.  For everything else, use your judgment.

## Tenses

Make sure to use the appropriate tense in each part of the report. If you're reporting what you did (e.g. in the Methods) or what someone did in another study (e.g. in the Introduction or Discussion) then use the past tense. Also use the past tense in the Results, because the results were recorded/found in the past. However, when discussing context and theory currently held to be true (in the Introduction and Discussion), make sure to use the present tense. Future tense will typically only be used when suggesting a potential future follow-up study/studies, usually in a small section at the end of the Discussion.