<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>D Performing some useful analyses in R | Bio 373L Survival Guide</title>
  <meta name="description" content="Writing advice for Field Ecology." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="D Performing some useful analyses in R | Bio 373L Survival Guide" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Writing advice for Field Ecology." />
  <meta name="github-repo" content="Christopher-Peterson/Bio373L-Book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="D Performing some useful analyses in R | Bio 373L Survival Guide" />
  
  <meta name="twitter:description" content="Writing advice for Field Ecology." />
  

<meta name="author" content="Christopher R. Peterson" />


<meta name="date" content="2021-08-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="dplyr-tutorial.html"/>
<link rel="next" href="tidyr-tutorial.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bio 373L Survival Guide</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="structure.html"><a href="structure.html"><i class="fa fa-check"></i><b>1</b> Writing Lab Reports: Structure</a><ul>
<li class="chapter" data-level="1.1" data-path="structure.html"><a href="structure.html#structure-overview"><i class="fa fa-check"></i><b>1.1</b> Structure Overview</a></li>
<li class="chapter" data-level="1.2" data-path="structure.html"><a href="structure.html#abstract"><i class="fa fa-check"></i><b>1.2</b> Abstract</a></li>
<li class="chapter" data-level="1.3" data-path="structure.html"><a href="structure.html#introduction"><i class="fa fa-check"></i><b>1.3</b> Introduction</a></li>
<li class="chapter" data-level="1.4" data-path="structure.html"><a href="structure.html#methods"><i class="fa fa-check"></i><b>1.4</b> Methods</a></li>
<li class="chapter" data-level="1.5" data-path="structure.html"><a href="structure.html#results"><i class="fa fa-check"></i><b>1.5</b> Results</a><ul>
<li class="chapter" data-level="1.5.1" data-path="structure.html"><a href="structure.html#reporting-statistics"><i class="fa fa-check"></i><b>1.5.1</b> Reporting statistics</a></li>
<li class="chapter" data-level="1.5.2" data-path="structure.html"><a href="structure.html#do-not-interpret-your-data-here"><i class="fa fa-check"></i><b>1.5.2</b> Do not interpret your data here</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="structure.html"><a href="structure.html#discussion"><i class="fa fa-check"></i><b>1.6</b> Discussion</a></li>
<li class="chapter" data-level="1.7" data-path="structure.html"><a href="structure.html#literature-cited"><i class="fa fa-check"></i><b>1.7</b> Literature Cited</a></li>
<li class="chapter" data-level="1.8" data-path="structure.html"><a href="structure.html#common-mistakes-for-particular-sections"><i class="fa fa-check"></i><b>1.8</b> Common Mistakes for particular sections</a><ul>
<li class="chapter" data-level="1.8.1" data-path="structure.html"><a href="structure.html#introduction-and-discussion"><i class="fa fa-check"></i><b>1.8.1</b> Introduction and Discussion</a></li>
<li class="chapter" data-level="1.8.2" data-path="structure.html"><a href="structure.html#results-1"><i class="fa fa-check"></i><b>1.8.2</b> Results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="style.html"><a href="style.html"><i class="fa fa-check"></i><b>2</b> Writing Lab Reports: Style</a><ul>
<li class="chapter" data-level="2.1" data-path="style.html"><a href="style.html#be-concise"><i class="fa fa-check"></i><b>2.1</b> Be Concise</a></li>
<li class="chapter" data-level="2.2" data-path="style.html"><a href="style.html#sentence-structure"><i class="fa fa-check"></i><b>2.2</b> Sentence Structure</a></li>
<li class="chapter" data-level="2.3" data-path="style.html"><a href="style.html#passive-voice"><i class="fa fa-check"></i><b>2.3</b> Passive Voice</a></li>
<li class="chapter" data-level="2.4" data-path="style.html"><a href="style.html#word-choice"><i class="fa fa-check"></i><b>2.4</b> Word Choice</a></li>
<li class="chapter" data-level="2.5" data-path="style.html"><a href="style.html#scientific-and-common-names"><i class="fa fa-check"></i><b>2.5</b> Scientific and Common Names</a></li>
<li class="chapter" data-level="2.6" data-path="style.html"><a href="style.html#other-grammar"><i class="fa fa-check"></i><b>2.6</b> Other Grammar</a></li>
<li class="chapter" data-level="2.7" data-path="style.html"><a href="style.html#commonly-confused-definitions"><i class="fa fa-check"></i><b>2.7</b> Commonly Confused Definitions</a></li>
<li class="chapter" data-level="2.8" data-path="style.html"><a href="style.html#significant-digits"><i class="fa fa-check"></i><b>2.8</b> Significant Digits</a></li>
<li class="chapter" data-level="2.9" data-path="style.html"><a href="style.html#tenses"><i class="fa fa-check"></i><b>2.9</b> Tenses</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="figures.html"><a href="figures.html"><i class="fa fa-check"></i><b>3</b> Figures and Tables</a><ul>
<li class="chapter" data-level="3.1" data-path="figures.html"><a href="figures.html#captions"><i class="fa fa-check"></i><b>3.1</b> Captions</a></li>
<li class="chapter" data-level="3.2" data-path="figures.html"><a href="figures.html#figures"><i class="fa fa-check"></i><b>3.2</b> Figures</a><ul>
<li class="chapter" data-level="3.2.1" data-path="figures.html"><a href="figures.html#specific-figure-guidelines"><i class="fa fa-check"></i><b>3.2.1</b> Specific Figure Guidelines</a></li>
<li class="chapter" data-level="3.2.2" data-path="figures.html"><a href="figures.html#be-concise-1"><i class="fa fa-check"></i><b>3.2.2</b> Be Concise</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="figures.html"><a href="figures.html#some-example-figures"><i class="fa fa-check"></i><b>3.3</b> Some Example Figures</a><ul>
<li class="chapter" data-level="3.3.1" data-path="figures.html"><a href="figures.html#general-formatting"><i class="fa fa-check"></i><b>3.3.1</b> General Formatting</a></li>
<li class="chapter" data-level="3.3.2" data-path="figures.html"><a href="figures.html#continuous-response-categorical-predictors"><i class="fa fa-check"></i><b>3.3.2</b> Continuous response, categorical predictors</a></li>
<li class="chapter" data-level="3.3.3" data-path="figures.html"><a href="figures.html#categorical-count-or-frequency-responses"><i class="fa fa-check"></i><b>3.3.3</b> Categorical, count, or frequency responses</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="figures.html"><a href="figures.html#tables"><i class="fa fa-check"></i><b>3.4</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lab1.html"><a href="lab1.html"><i class="fa fa-check"></i><b>4</b> Lab 1: Succession</a><ul>
<li class="chapter" data-level="4.1" data-path="lab1.html"><a href="lab1.html#introduction-to-the-lab"><i class="fa fa-check"></i><b>4.1</b> Introduction to the lab</a></li>
<li class="chapter" data-level="4.2" data-path="lab1.html"><a href="lab1.html#materials-and-methods"><i class="fa fa-check"></i><b>4.2</b> Materials and Methods</a><ul>
<li class="chapter" data-level="4.2.1" data-path="lab1.html"><a href="lab1.html#bfl-habitat-regions"><i class="fa fa-check"></i><b>4.2.1</b> BFL habitat regions</a></li>
<li class="chapter" data-level="4.2.2" data-path="lab1.html"><a href="lab1.html#data-collection"><i class="fa fa-check"></i><b>4.2.2</b> Data Collection</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="lab1.html"><a href="lab1.html#analysis-to-perform"><i class="fa fa-check"></i><b>4.3</b> Analysis to perform</a><ul>
<li class="chapter" data-level="4.3.1" data-path="lab1.html"><a href="lab1.html#canopy-tree-density"><i class="fa fa-check"></i><b>4.3.1</b> Canopy tree density</a></li>
<li class="chapter" data-level="4.3.2" data-path="lab1.html"><a href="lab1.html#species-by-habitat-and-life-stage"><i class="fa fa-check"></i><b>4.3.2</b> Species by habitat and life stage</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="lab1.html"><a href="lab1.html#discussion-1"><i class="fa fa-check"></i><b>4.4</b> Discussion</a></li>
<li class="chapter" data-level="4.5" data-path="lab1.html"><a href="lab1.html#general-comments-post-review"><i class="fa fa-check"></i><b>4.5</b> General Comments (Post-Review)</a><ul>
<li class="chapter" data-level="4.5.1" data-path="lab1.html"><a href="lab1.html#figures-1"><i class="fa fa-check"></i><b>4.5.1</b> Figures</a></li>
<li class="chapter" data-level="4.5.2" data-path="lab1.html"><a href="lab1.html#write-this-like-youre-trying-to-publish-it"><i class="fa fa-check"></i><b>4.5.2</b> Write this like you're trying to publish it</a></li>
<li class="chapter" data-level="4.5.3" data-path="lab1.html"><a href="lab1.html#describe-the-habitats"><i class="fa fa-check"></i><b>4.5.3</b> Describe the habitats</a></li>
<li class="chapter" data-level="4.5.4" data-path="lab1.html"><a href="lab1.html#the-analysis"><i class="fa fa-check"></i><b>4.5.4</b> The Analysis</a></li>
<li class="chapter" data-level="4.5.5" data-path="lab1.html"><a href="lab1.html#keeping-things-in-the-right-sections"><i class="fa fa-check"></i><b>4.5.5</b> Keeping things in the right sections</a></li>
<li class="chapter" data-level="4.5.6" data-path="lab1.html"><a href="lab1.html#basic-style-and-format-rules"><i class="fa fa-check"></i><b>4.5.6</b> Basic style and format rules</a></li>
<li class="chapter" data-level="4.5.7" data-path="lab1.html"><a href="lab1.html#other-comments"><i class="fa fa-check"></i><b>4.5.7</b> Other Comments</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="Lab2.html"><a href="Lab2.html"><i class="fa fa-check"></i><b>5</b> Lab 2: Woodland Heterogeneity</a><ul>
<li class="chapter" data-level="5.1" data-path="Lab2.html"><a href="Lab2.html#introduction-background"><i class="fa fa-check"></i><b>5.1</b> Introduction &amp; background</a></li>
<li class="chapter" data-level="5.2" data-path="Lab2.html"><a href="Lab2.html#questions-and-hypotheses"><i class="fa fa-check"></i><b>5.2</b> Questions and Hypotheses</a></li>
<li class="chapter" data-level="5.3" data-path="Lab2.html"><a href="Lab2.html#field-methods"><i class="fa fa-check"></i><b>5.3</b> Field Methods</a></li>
<li class="chapter" data-level="5.4" data-path="Lab2.html"><a href="Lab2.html#analyses"><i class="fa fa-check"></i><b>5.4</b> Analyses</a><ul>
<li class="chapter" data-level="5.4.1" data-path="Lab2.html"><a href="Lab2.html#calibrating-canopy-estimates"><i class="fa fa-check"></i><b>5.4.1</b> Calibrating canopy estimates</a></li>
<li class="chapter" data-level="5.4.2" data-path="Lab2.html"><a href="Lab2.html#relationship-between-canopy-and-ground-cover"><i class="fa fa-check"></i><b>5.4.2</b> Relationship between canopy and ground cover</a></li>
<li class="chapter" data-level="5.4.3" data-path="Lab2.html"><a href="Lab2.html#quantifying-the-spatial-mosaic"><i class="fa fa-check"></i><b>5.4.3</b> Quantifying the spatial mosaic</a></li>
<li class="chapter" data-level="5.4.4" data-path="Lab2.html"><a href="Lab2.html#historical-trends"><i class="fa fa-check"></i><b>5.4.4</b> Historical Trends</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="Lab3.html"><a href="Lab3.html"><i class="fa fa-check"></i><b>6</b> Lab 3: Ant Community Ecology</a><ul>
<li class="chapter" data-level="6.1" data-path="Lab3.html"><a href="Lab3.html#background"><i class="fa fa-check"></i><b>6.1</b> Background</a></li>
<li class="chapter" data-level="6.2" data-path="Lab3.html"><a href="Lab3.html#questions-and-hypotheses-1"><i class="fa fa-check"></i><b>6.2</b> Questions and hypotheses</a></li>
<li class="chapter" data-level="6.3" data-path="Lab3.html"><a href="Lab3.html#methods-1"><i class="fa fa-check"></i><b>6.3</b> Methods</a><ul>
<li class="chapter" data-level="6.3.1" data-path="Lab3.html"><a href="Lab3.html#bait-survey"><i class="fa fa-check"></i><b>6.3.1</b> Bait Survey</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="Lab3.html"><a href="Lab3.html#analysis"><i class="fa fa-check"></i><b>6.4</b> Analysis</a><ul>
<li class="chapter" data-level="6.4.1" data-path="Lab3.html"><a href="Lab3.html#s.-invicta-habitat-preference"><i class="fa fa-check"></i><b>6.4.1</b> <em>S. invicta</em> habitat preference</a></li>
<li class="chapter" data-level="6.4.2" data-path="Lab3.html"><a href="Lab3.html#ant-community-differences"><i class="fa fa-check"></i><b>6.4.2</b> Ant community differences</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="Lab_phorid.html"><a href="Lab_phorid.html"><i class="fa fa-check"></i><b>7</b> Lab 4: Parasitoid impacts on host foraging behavior: Phorid flies and fire ants</a><ul>
<li class="chapter" data-level="7.1" data-path="Lab_phorid.html"><a href="Lab_phorid.html#background-1"><i class="fa fa-check"></i><b>7.1</b> Background</a><ul>
<li class="chapter" data-level="7.1.1" data-path="Lab_phorid.html"><a href="Lab_phorid.html#fire-ants-and-phorid-flies"><i class="fa fa-check"></i><b>7.1.1</b> Fire ants and phorid flies</a></li>
<li class="chapter" data-level="7.1.2" data-path="Lab_phorid.html"><a href="Lab_phorid.html#fire-ants-natural-history"><i class="fa fa-check"></i><b>7.1.2</b> Fire ants natural history</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="Lab_phorid.html"><a href="Lab_phorid.html#objectives"><i class="fa fa-check"></i><b>7.2</b> Objectives</a></li>
<li class="chapter" data-level="7.3" data-path="Lab_phorid.html"><a href="Lab_phorid.html#methods-2"><i class="fa fa-check"></i><b>7.3</b> Methods</a><ul>
<li class="chapter" data-level="7.3.1" data-path="Lab_phorid.html"><a href="Lab_phorid.html#phorid-impact-on-fire-ant-foraging"><i class="fa fa-check"></i><b>7.3.1</b> Phorid impact on fire ant foraging</a></li>
<li class="chapter" data-level="7.3.2" data-path="Lab_phorid.html"><a href="Lab_phorid.html#using-the-hobo-mx2303-data-logger"><i class="fa fa-check"></i><b>7.3.2</b> Using the HOBO MX2303 data logger</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="Lab_phorid.html"><a href="Lab_phorid.html#analysis-1"><i class="fa fa-check"></i><b>7.4</b> Analysis</a><ul>
<li class="chapter" data-level="7.4.1" data-path="Lab_phorid.html"><a href="Lab_phorid.html#effect-of-phorids-on-ant-foraging"><i class="fa fa-check"></i><b>7.4.1</b> Effect of phorids on ant foraging</a></li>
<li class="chapter" data-level="7.4.2" data-path="Lab_phorid.html"><a href="Lab_phorid.html#effects-of-environmental-conditions"><i class="fa fa-check"></i><b>7.4.2</b> Effects of environmental conditions</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="Lab_phorid.html"><a href="Lab_phorid.html#discussion-2"><i class="fa fa-check"></i><b>7.5</b> Discussion</a></li>
<li class="chapter" data-level="7.6" data-path="Lab_phorid.html"><a href="Lab_phorid.html#some-questions-from-previou-semesters"><i class="fa fa-check"></i><b>7.6</b> Some questions from previou semesters:</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="Lab_MRR.html"><a href="Lab_MRR.html"><i class="fa fa-check"></i><b>8</b> Lab 5: Mark-Release-Recapture with <em>Heliconius</em></a><ul>
<li class="chapter" data-level="8.1" data-path="Lab_MRR.html"><a href="Lab_MRR.html#introduction-1"><i class="fa fa-check"></i><b>8.1</b> Introduction</a><ul>
<li class="chapter" data-level="8.1.1" data-path="Lab_MRR.html"><a href="Lab_MRR.html#the-lincoln-petersen-model"><i class="fa fa-check"></i><b>8.1.1</b> The Lincoln-Petersen model</a></li>
<li class="chapter" data-level="8.1.2" data-path="Lab_MRR.html"><a href="Lab_MRR.html#heliconius-butterflies"><i class="fa fa-check"></i><b>8.1.2</b> <em>Heliconius</em> butterflies</a></li>
<li class="chapter" data-level="8.1.3" data-path="Lab_MRR.html"><a href="Lab_MRR.html#hardy-weinberg-equilbrium"><i class="fa fa-check"></i><b>8.1.3</b> Hardy-Weinberg Equilbrium</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="Lab_MRR.html"><a href="Lab_MRR.html#questions-and-hypotheses-2"><i class="fa fa-check"></i><b>8.2</b> Questions and hypotheses</a></li>
<li class="chapter" data-level="8.3" data-path="Lab_MRR.html"><a href="Lab_MRR.html#field-methods-1"><i class="fa fa-check"></i><b>8.3</b> Field Methods</a></li>
<li class="chapter" data-level="8.4" data-path="Lab_MRR.html"><a href="Lab_MRR.html#analysis-2"><i class="fa fa-check"></i><b>8.4</b> Analysis</a><ul>
<li class="chapter" data-level="8.4.1" data-path="Lab_MRR.html"><a href="Lab_MRR.html#effect-of-sampling-intensity-on-lincoln-petersen-hatn-estimates"><i class="fa fa-check"></i><b>8.4.1</b> Effect of sampling intensity on Lincoln-Petersen <span class="math inline">\(\hat{N}\)</span> estimates</a></li>
<li class="chapter" data-level="8.4.2" data-path="Lab_MRR.html"><a href="Lab_MRR.html#sex-ratios"><i class="fa fa-check"></i><b>8.4.2</b> Sex ratios</a></li>
<li class="chapter" data-level="8.4.3" data-path="Lab_MRR.html"><a href="Lab_MRR.html#comparison-of-lincoln-petersen-with-alternative-method"><i class="fa fa-check"></i><b>8.4.3</b> Comparison of Lincoln-Petersen with alternative method</a></li>
<li class="chapter" data-level="8.4.4" data-path="Lab_MRR.html"><a href="Lab_MRR.html#hardy-weinberg"><i class="fa fa-check"></i><b>8.4.4</b> Hardy-Weinberg</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="Lab_MRR.html"><a href="Lab_MRR.html#discussion-3"><i class="fa fa-check"></i><b>8.5</b> Discussion</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="working-with-r.html"><a href="working-with-r.html"><i class="fa fa-check"></i><b>A</b> Working with R</a><ul>
<li class="chapter" data-level="A.1" data-path="working-with-r.html"><a href="working-with-r.html#introduction-to-rstudio"><i class="fa fa-check"></i><b>A.1</b> Introduction to RStudio</a><ul>
<li class="chapter" data-level="A.1.1" data-path="working-with-r.html"><a href="working-with-r.html#rstudio-projects"><i class="fa fa-check"></i><b>A.1.1</b> RStudio Projects</a></li>
<li class="chapter" data-level="A.1.2" data-path="working-with-r.html"><a href="working-with-r.html#customizing-rstudio"><i class="fa fa-check"></i><b>A.1.2</b> Customizing RStudio</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="working-with-r.html"><a href="working-with-r.html#r-basics"><i class="fa fa-check"></i><b>A.2</b> R basics</a><ul>
<li class="chapter" data-level="A.2.1" data-path="working-with-r.html"><a href="working-with-r.html#statements-vectors"><i class="fa fa-check"></i><b>A.2.1</b> Statements &amp; vectors</a></li>
<li class="chapter" data-level="A.2.2" data-path="working-with-r.html"><a href="working-with-r.html#variables"><i class="fa fa-check"></i><b>A.2.2</b> Variables</a></li>
<li class="chapter" data-level="A.2.3" data-path="working-with-r.html"><a href="working-with-r.html#reading-working-with-data-frames"><i class="fa fa-check"></i><b>A.2.3</b> Reading &amp; working with data frames</a></li>
<li class="chapter" data-level="A.2.4" data-path="working-with-r.html"><a href="working-with-r.html#functions"><i class="fa fa-check"></i><b>A.2.4</b> Functions</a></li>
<li class="chapter" data-level="A.2.5" data-path="working-with-r.html"><a href="working-with-r.html#getting-help"><i class="fa fa-check"></i><b>A.2.5</b> Getting Help</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html"><i class="fa fa-check"></i><b>B</b> Making graphs in R with <code>ggplot2</code></a><ul>
<li class="chapter" data-level="B.1" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#components-of-a-plot"><i class="fa fa-check"></i><b>B.1</b> Components of a plot</a></li>
<li class="chapter" data-level="B.2" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#aesthetics-and-scales"><i class="fa fa-check"></i><b>B.2</b> Aesthetics and scales</a><ul>
<li class="chapter" data-level="B.2.1" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#color"><i class="fa fa-check"></i><b>B.2.1</b> Color</a></li>
<li class="chapter" data-level="B.2.2" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#shape"><i class="fa fa-check"></i><b>B.2.2</b> Shape</a></li>
<li class="chapter" data-level="B.2.3" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#size"><i class="fa fa-check"></i><b>B.2.3</b> Size</a></li>
<li class="chapter" data-level="B.2.4" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#fixed-aesthetics"><i class="fa fa-check"></i><b>B.2.4</b> Fixed aesthetics</a></li>
<li class="chapter" data-level="B.2.5" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#combining-aesthetics"><i class="fa fa-check"></i><b>B.2.5</b> Combining aesthetics</a></li>
</ul></li>
<li class="chapter" data-level="B.3" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#geometry"><i class="fa fa-check"></i><b>B.3</b> Geometry</a><ul>
<li class="chapter" data-level="B.3.1" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#continuous-x-no-y"><i class="fa fa-check"></i><b>B.3.1</b> Continuous X, no Y</a></li>
<li class="chapter" data-level="B.3.2" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#ggp_discx_conty"><i class="fa fa-check"></i><b>B.3.2</b> Discrete X, continuous Y</a></li>
<li class="chapter" data-level="B.3.3" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#continuous-x-and-y"><i class="fa fa-check"></i><b>B.3.3</b> Continuous X and Y</a></li>
<li class="chapter" data-level="B.3.4" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#time-series-data"><i class="fa fa-check"></i><b>B.3.4</b> Time series data</a></li>
<li class="chapter" data-level="B.3.5" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#discrete-x-and-y"><i class="fa fa-check"></i><b>B.3.5</b> Discrete X and Y</a></li>
</ul></li>
<li class="chapter" data-level="B.4" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#facets"><i class="fa fa-check"></i><b>B.4</b> Facets</a></li>
<li class="chapter" data-level="B.5" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#changing-the-theme-axis-titles-other-visual-elements"><i class="fa fa-check"></i><b>B.5</b> Changing the theme, axis titles, &amp; other visual elements</a></li>
<li class="chapter" data-level="B.6" data-path="ggplot-tutorial.html"><a href="ggplot-tutorial.html#more-references"><i class="fa fa-check"></i><b>B.6</b> More references</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="dplyr-tutorial.html"><a href="dplyr-tutorial.html"><i class="fa fa-check"></i><b>C</b> Data manipulation with <code>dplyr</code></a><ul>
<li class="chapter" data-level="C.1" data-path="dplyr-tutorial.html"><a href="dplyr-tutorial.html#the-pipe"><i class="fa fa-check"></i><b>C.1</b> The Pipe (%&gt;%)</a></li>
<li class="chapter" data-level="C.2" data-path="dplyr-tutorial.html"><a href="dplyr-tutorial.html#addingmodifying-columns-mutate"><i class="fa fa-check"></i><b>C.2</b> Adding/modifying columns (mutate)</a></li>
<li class="chapter" data-level="C.3" data-path="dplyr-tutorial.html"><a href="dplyr-tutorial.html#subsetting-by-row-filter"><i class="fa fa-check"></i><b>C.3</b> Subsetting by row (filter)</a></li>
<li class="chapter" data-level="C.4" data-path="dplyr-tutorial.html"><a href="dplyr-tutorial.html#subsetting-by-column-select"><i class="fa fa-check"></i><b>C.4</b> Subsetting by column (select)</a></li>
<li class="chapter" data-level="C.5" data-path="dplyr-tutorial.html"><a href="dplyr-tutorial.html#sorting-by-columns-arrange"><i class="fa fa-check"></i><b>C.5</b> Sorting by columns (arrange)</a></li>
<li class="chapter" data-level="C.6" data-path="dplyr-tutorial.html"><a href="dplyr-tutorial.html#summarizing-data"><i class="fa fa-check"></i><b>C.6</b> Summarizing data</a></li>
<li class="chapter" data-level="C.7" data-path="dplyr-tutorial.html"><a href="dplyr-tutorial.html#group-operations"><i class="fa fa-check"></i><b>C.7</b> Group Operations</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="r-analysis-tutorial.html"><a href="r-analysis-tutorial.html"><i class="fa fa-check"></i><b>D</b> Performing some useful analyses in R</a><ul>
<li class="chapter" data-level="D.1" data-path="r-analysis-tutorial.html"><a href="r-analysis-tutorial.html#a-note-on-factors"><i class="fa fa-check"></i><b>D.1</b> A note on factors</a></li>
<li class="chapter" data-level="D.2" data-path="r-analysis-tutorial.html"><a href="r-analysis-tutorial.html#comparing-categorical-frequencies-contingency-tables-related-analyses"><i class="fa fa-check"></i><b>D.2</b> Comparing categorical frequencies (Contingency Tables &amp; related analyses)</a><ul>
<li class="chapter" data-level="D.2.1" data-path="r-analysis-tutorial.html"><a href="r-analysis-tutorial.html#contingency-tables"><i class="fa fa-check"></i><b>D.2.1</b> Contingency Tables</a></li>
<li class="chapter" data-level="D.2.2" data-path="r-analysis-tutorial.html"><a href="r-analysis-tutorial.html#chi-squared-fishers-exact-tests"><i class="fa fa-check"></i><b>D.2.2</b> Chi-squared &amp; Fisher's Exact Tests</a></li>
</ul></li>
<li class="chapter" data-level="D.3" data-path="r-analysis-tutorial.html"><a href="r-analysis-tutorial.html#linear-models-regression-anova-and-t-tests"><i class="fa fa-check"></i><b>D.3</b> Linear Models: Regression, ANOVA, and t-tests</a><ul>
<li class="chapter" data-level="D.3.1" data-path="r-analysis-tutorial.html"><a href="r-analysis-tutorial.html#regression"><i class="fa fa-check"></i><b>D.3.1</b> Regression</a></li>
<li class="chapter" data-level="D.3.2" data-path="r-analysis-tutorial.html"><a href="r-analysis-tutorial.html#anova"><i class="fa fa-check"></i><b>D.3.2</b> ANOVA</a></li>
<li class="chapter" data-level="D.3.3" data-path="r-analysis-tutorial.html"><a href="r-analysis-tutorial.html#comparing-two-means-t-tests"><i class="fa fa-check"></i><b>D.3.3</b> Comparing two means (t-tests)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="E" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html"><i class="fa fa-check"></i><b>E</b> Wrangling, reshaping, and tidying data with <code>tidyr</code></a><ul>
<li class="chapter" data-level="E.1" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#tidy-data"><i class="fa fa-check"></i><b>E.1</b> Tidy data</a></li>
<li class="chapter" data-level="E.2" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#pivot-longer-tutorial"><i class="fa fa-check"></i><b>E.2</b> Going from many columns to many rows: <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="E.3" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#separate-tutorial"><i class="fa fa-check"></i><b>E.3</b> Splitting and merging columns: <code>separate() and unite()</code></a></li>
<li class="chapter" data-level="E.4" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#pivot-longer-multi-tutorial"><i class="fa fa-check"></i><b>E.4</b> Pivoting multiple columns</a><ul>
<li class="chapter" data-level="E.4.1" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#combining-pivot_longer-with-summarise"><i class="fa fa-check"></i><b>E.4.1</b> Combining <code>pivot_longer()</code> with <code>summarise()</code></a></li>
</ul></li>
<li class="chapter" data-level="E.5" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#pivot-wider-tutorial"><i class="fa fa-check"></i><b>E.5</b> Going from many rows to many columns: <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="E.6" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#combining-data-frames-in-progress"><i class="fa fa-check"></i><b>E.6</b> Combining data frames (In Progress)</a><ul>
<li class="chapter" data-level="E.6.1" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#binding-rows"><i class="fa fa-check"></i><b>E.6.1</b> Binding rows</a></li>
<li class="chapter" data-level="E.6.2" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#binding-columns-by-position"><i class="fa fa-check"></i><b>E.6.2</b> Binding columns by position</a></li>
<li class="chapter" data-level="E.6.3" data-path="tidyr-tutorial.html"><a href="tidyr-tutorial.html#joining-rows-by-value"><i class="fa fa-check"></i><b>E.6.3</b> Joining rows by value</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="F" data-path="vegan-tutorial.html"><a href="vegan-tutorial.html"><i class="fa fa-check"></i><b>F</b> Community ecology analyses with <code>vegan</code></a><ul>
<li class="chapter" data-level="F.1" data-path="vegan-tutorial.html"><a href="vegan-tutorial.html#setting-up-the-data"><i class="fa fa-check"></i><b>F.1</b> Setting up the data</a></li>
<li class="chapter" data-level="F.2" data-path="vegan-tutorial.html"><a href="vegan-tutorial.html#jaccard-similarity"><i class="fa fa-check"></i><b>F.2</b> Jaccard similarity</a></li>
<li class="chapter" data-level="F.3" data-path="vegan-tutorial.html"><a href="vegan-tutorial.html#species-accumulation-curves"><i class="fa fa-check"></i><b>F.3</b> Species Accumulation Curves</a></li>
<li class="chapter" data-level="F.4" data-path="vegan-tutorial.html"><a href="vegan-tutorial.html#rank-abundance-curves"><i class="fa fa-check"></i><b>F.4</b> Rank Abundance Curves</a></li>
<li class="chapter" data-level="F.5" data-path="vegan-tutorial.html"><a href="vegan-tutorial.html#shannon-index-diversity"><i class="fa fa-check"></i><b>F.5</b> Shannon Index &amp; Diversity</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Bio 373L Survival Guide</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="r-analysis-tutorial" class="section level1">
<h1><span class="header-section-number">D</span> Performing some useful analyses in R</h1>
<p>I'm going to give some examples of how to do common analyses you'll need for this class. I won't be spending much time on the statistical assumptions or diagnostics.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse) 
<span class="kw">library</span>(cowplot)
<span class="kw">theme_set</span>(<span class="kw">theme_cowplot</span>())
lizards &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;example_data/anoles.csv&quot;</span>) <span class="co"># See Appendix A if you don&#39;t have this data</span></code></pre></div>
<div id="a-note-on-factors" class="section level2">
<h2><span class="header-section-number">D.1</span> A note on factors</h2>
<p>R has two ways of representing textual data: character vectors (also called strings) and factors.</p>
<ul>
<li>Character vectors are just text; they have no inherent underlying meaning.</li>
<li>Factors are a data type with a specific number of levels; they're often used to represent different experimental treatments. Examples could include {low, medium, high} or {control, treatment}. Each level of a factor is associated with a number.</li>
</ul>
<p>For the most part, it's easier and safer to work with character vectors. Most functions we'll be using know how to convert them when it's necessary.</p>
<p>One important thing to note is that <code>ggplot</code> arranges character vectors alphabetically on its categorical scales, but orders factors by their level number. Thus, to change the order of categorical x-axes (and other scales), you need to make your categories into a factor. This is done with the <code>fct_inorder</code>, <code>fct_infreq</code>, and related functions, which are part of the <code>forcats</code> package and loaded with tidyverse. The easiest one to use is <code>fct_inorder</code>, which changes the level values to be in the order of your data; when combined with <code>arrange()</code> and other <code>dplyr</code> functions, this is quite flexible and powerful. For more information on these and other factor functions, take a look at the <a href="http://forcats.tidyverse.org">forcats website</a>.</p>
<p>If you want to manually create a factor, you can use the <code>factor</code> command, which is in base R (no package).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">color_levels =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Red&quot;</span>,<span class="st">&quot;Green&quot;</span>,<span class="st">&quot;Blue&quot;</span>)
<span class="co"># Randomly select 20 colors from color_levels</span>
color_example =<span class="st"> </span><span class="kw">sample</span>(color_levels, <span class="dt">size =</span> <span class="dv">20</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)
color_example
##  [1] &quot;Green&quot; &quot;Blue&quot;  &quot;Green&quot; &quot;Green&quot; &quot;Blue&quot;  &quot;Green&quot; &quot;Green&quot; &quot;Green&quot; &quot;Blue&quot; 
## [10] &quot;Blue&quot;  &quot;Red&quot;   &quot;Blue&quot;  &quot;Green&quot; &quot;Green&quot; &quot;Blue&quot;  &quot;Green&quot; &quot;Red&quot;   &quot;Blue&quot; 
## [19] &quot;Blue&quot;  &quot;Blue&quot;

<span class="co"># Convert it into a factor</span>
color_as_factor =<span class="st"> </span><span class="kw">factor</span>(color_example, <span class="dt">levels =</span> color_levels)
color_as_factor
##  [1] Green Blue  Green Green Blue  Green Green Green Blue  Blue  Red   Blue 
## [13] Green Green Blue  Green Red   Blue  Blue  Blue 
## Levels: Red Green Blue</code></pre></div>
</div>
<div id="comparing-categorical-frequencies-contingency-tables-related-analyses" class="section level2">
<h2><span class="header-section-number">D.2</span> Comparing categorical frequencies (Contingency Tables &amp; related analyses)</h2>
<p>These tests generally compare the frequencies of count data.</p>
<div id="contingency-tables" class="section level3">
<h3><span class="header-section-number">D.2.1</span> Contingency Tables</h3>
<p>The easiest way to make a contingency table is from a data frame where each column is a categorical variable you want in the table &amp; each row is an observation. Let's say we wanted to create a color morph by perch type contingency with our lizard data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">color_by_perch_tbl &lt;-<span class="st"> </span>lizards <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Color_morph, Perch_type) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># select only the columns you want</span>
<span class="st">  </span><span class="kw">table</span>()  <span class="co"># feed them into the table command</span>
color_by_perch_tbl
##            Perch_type
## Color_morph Building Other Shrub Tree
##       Blue        17    41    27  130
##       Brown       31    25    25  140
##       Green       30    25    32  134</code></pre></div>
<p>If you want to switch your contingency table from counts to frequencies, just divide it by its sum:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">color_by_perch_tbl <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(color_by_perch_tbl)
##            Perch_type
## Color_morph   Building      Other      Shrub       Tree
##       Blue  0.02587519 0.06240487 0.04109589 0.19786910
##       Brown 0.04718417 0.03805175 0.03805175 0.21308980
##       Green 0.04566210 0.03805175 0.04870624 0.20395738</code></pre></div>
</div>
<div id="chi-squared-fishers-exact-tests" class="section level3">
<h3><span class="header-section-number">D.2.2</span> Chi-squared &amp; Fisher's Exact Tests</h3>
<p>Once you have a contingency table, you can test for independence between the rows and columns. This provides you with your test statistic (<code>X-squared</code>), degrees of freedom, and p-value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">chisq.test</span>(color_by_perch_tbl)
## 
##  Pearson&#39;s Chi-squared test
## 
## data:  color_by_perch_tbl
## X-squared = 11.603, df = 6, p-value = 0.07143</code></pre></div>
<p>Chi-squared tests assume that there's at least five observations in each cell of the contingency table. If this fails, then the resulting values aren't accurate. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">site_a_contingency &lt;-<span class="st"> </span>lizards <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(Site <span class="op">==</span><span class="st"> &quot;A&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># cut down the data size</span>
<span class="st">  </span><span class="kw">select</span>(Color_morph, Perch_type) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># select only the columns you want</span>
<span class="st">  </span><span class="kw">table</span>()  <span class="co"># feed them into the table command</span>
<span class="kw">print</span>(site_a_contingency)
##            Perch_type
## Color_morph Building Other Shrub Tree
##       Blue         1     3     1    5
##       Brown        0     0     2   11
##       Green        1     1     0    1
<span class="kw">chisq.test</span>(site_a_contingency)
## Warning in chisq.test(site_a_contingency): Chi-squared approximation may be
## incorrect
## 
##  Pearson&#39;s Chi-squared test
## 
## data:  site_a_contingency
## X-squared = 9.752, df = 6, p-value = 0.1355</code></pre></div>
<p>Note the warning that &quot;Chi-squared approximation may be incorrect.&quot; In this case, it's a good idea to run the Fisher's exact test, which investigates the same null hypotheses, but works with low counts. Fisher's test is less powerful than the Chi-squared test, so it should only be used when it's the only option.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fisher.test</span>(site_a_contingency)
## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  site_a_contingency
## p-value = 0.06251
## alternative hypothesis: two.sided</code></pre></div>
<p>You can also run a chi-squared or Fisher's exact test directly on two vectors or data frame columns:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">chisq.test</span>(lizards<span class="op">$</span>Color_morph, lizards<span class="op">$</span>Perch_type)
## 
##  Pearson&#39;s Chi-squared test
## 
## data:  lizards$Color_morph and lizards$Perch_type
## X-squared = 11.603, df = 6, p-value = 0.07143</code></pre></div>
</div>
</div>
<div id="linear-models-regression-anova-and-t-tests" class="section level2">
<h2><span class="header-section-number">D.3</span> Linear Models: Regression, ANOVA, and t-tests</h2>
<p>Linear regression and Analysis of Variance (ANOVA) are both special cases of the general linear model (LM), which fits a continuous response (y) to one or more predictors (x). You specify linear models in R with a <strong>formula</strong> syntax, which generally follows as: <code>response ~ predictor</code>. Combining this formula with the <code>lm()</code> function and a datset gives you the basis of a linear model.</p>
<div id="regression" class="section level3">
<h3><span class="header-section-number">D.3.1</span> Regression</h3>
<p>Lets say we wanted to see how snout-vent length (SVL) affects mass:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">simple_reg &lt;-<span class="st"> </span><span class="kw">lm</span>(Mass <span class="op">~</span><span class="st"> </span>SVL, <span class="dt">data =</span> lizards)
simple_reg
## 
## Call:
## lm(formula = Mass ~ SVL, data = lizards)
## 
## Coefficients:
## (Intercept)          SVL  
##     1.62577      0.08886</code></pre></div>
<p>By default, this creates an LM object, which tells us the regression coefficients. For a linear regression (continuous response), these tell us the regression equation; in this case, that for every <span class="math inline">\(1 \text{ mm}\)</span> increase in SVL, mass increases by <span class="math inline">\(0.089 \text{ g}\)</span>. Note that in this case, it may make sense to re-scale SVL to be in cm, so that the coefficient would be easier to interpret (e.g., use <code>lizards %&gt;% mutate(SVL_cm = SVL/10)</code>. To extract the coeficients directly, use:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(simple_reg)
## (Intercept)         SVL 
##   1.6257700   0.0888617</code></pre></div>
<p>For more information, use the summary function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(simple_reg)
## 
## Call:
## lm(formula = Mass ~ SVL, data = lizards)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.2672 -0.4699 -0.0530  0.3959  5.6050 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.625770   0.210781   7.713 4.59e-14 ***
## SVL         0.088862   0.003434  25.874  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.7661 on 655 degrees of freedom
## Multiple R-squared:  0.5055, Adjusted R-squared:  0.5047 
## F-statistic: 669.5 on 1 and 655 DF,  p-value: &lt; 2.2e-16</code></pre></div>
<p>The most important components of this are the <span class="math inline">\(R^2\)</span> (which is listed as <code>Multiple R-squared</code>), the standard errors and p-values for each of your coefficients (<code>Coefficients</code> section), and the overall F-statistic and p-value (the last line).</p>
<p>A quick note on p-values:</p>
<ol style="list-style-type: decimal">
<li>Don't base all of your interpretation on p-values; the <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> of a model are more important.</li>
<li>The overall p-value relates to how the whole model explains the variance in the data; the coefficient p-value relates to whether the specific coefficient is different from zero.<br />
</li>
<li>Coefficient-level p-values tend to be rather fragile, and shouldn't be used.</li>
</ol>
<div id="plotting-linear-regressions" class="section level4">
<h4><span class="header-section-number">D.3.1.1</span> Plotting linear regressions</h4>
<p>For a simple linear regression, <code>ggplot</code> can automatically plot the trendline (a.k.a., fitted values) and confidence intervals with <code>geom_smooth()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lizards <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">aes</span>(<span class="dt">x =</span> SVL, <span class="dt">y =</span> Mass) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="co"># use a linear regression</span>
              <span class="dt">se =</span> <span class="ot">TRUE</span>, <span class="co"># Include a confidence interval around the line</span>
              <span class="dt">level =</span> .<span class="dv">95</span>) <span class="co"># the level of the confidence interval; default = 95%</span></code></pre></div>
<p><img src="Bio373L-Book_files/figure-html/a4_lin_reg_plot1-1.png" width="672" /></p>
<p>For more complicated models, this approach may not work very well; it can be helpful to calculate the fitted values &amp; confidence intervals from the model object and plot them directly.</p>
<p>You can get these values directly with the <code>predict()</code> function. The code below calculates the trendline and 95% confidence interval for the regression, and adds them to a data frame with the original data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">simple_reg_predictions &lt;-<span class="st"> </span>simple_reg <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="co"># Predict fitted values wish 95% confidence intervals</span>
<span class="st">  </span><span class="kw">predict</span>(<span class="dt">interval =</span> <span class="st">&quot;confidence&quot;</span>, <span class="dt">level =</span> .<span class="dv">95</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="co"># The output of predict() is a matrix; that&#39;s hard to work with, so...</span>
<span class="st">  </span><span class="kw">as_tibble</span>() <span class="co"># we convert the output of predict() to a data frame (tibble)</span>
simple_reg_plot_data &lt;-<span class="st"> </span>lizards <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(SVL, Mass) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># we only need these columns</span>
<span class="st">  </span><span class="kw">bind_cols</span>(simple_reg_predictions) <span class="co"># adds columns of simple_reg_preds to our lizards</span>
<span class="kw">View</span>(simple_reg_plot_data)</code></pre></div>
<div style="border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:100%; ">
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
SVL
</th>
<th style="text-align:right;">
Mass
</th>
<th style="text-align:right;">
fit
</th>
<th style="text-align:right;">
lwr
</th>
<th style="text-align:right;">
upr
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
61.8
</td>
<td style="text-align:right;">
6.46
</td>
<td style="text-align:right;">
7.117423
</td>
<td style="text-align:right;">
7.058313
</td>
<td style="text-align:right;">
7.176533
</td>
</tr>
<tr>
<td style="text-align:right;">
57.1
</td>
<td style="text-align:right;">
5.82
</td>
<td style="text-align:right;">
6.699773
</td>
<td style="text-align:right;">
6.636126
</td>
<td style="text-align:right;">
6.763420
</td>
</tr>
<tr>
<td style="text-align:right;">
49.1
</td>
<td style="text-align:right;">
4.29
</td>
<td style="text-align:right;">
5.988879
</td>
<td style="text-align:right;">
5.890800
</td>
<td style="text-align:right;">
6.086959
</td>
</tr>
<tr>
<td style="text-align:right;">
51.2
</td>
<td style="text-align:right;">
5.29
</td>
<td style="text-align:right;">
6.175489
</td>
<td style="text-align:right;">
6.088343
</td>
<td style="text-align:right;">
6.262634
</td>
</tr>
<tr>
<td style="text-align:right;">
51.5
</td>
<td style="text-align:right;">
5.69
</td>
<td style="text-align:right;">
6.202147
</td>
<td style="text-align:right;">
6.116487
</td>
<td style="text-align:right;">
6.287808
</td>
</tr>
<tr>
<td style="text-align:right;">
45.3
</td>
<td style="text-align:right;">
5.84
</td>
<td style="text-align:right;">
5.651205
</td>
<td style="text-align:right;">
5.531606
</td>
<td style="text-align:right;">
5.770804
</td>
</tr>
<tr>
<td style="text-align:right;">
49.7
</td>
<td style="text-align:right;">
5.91
</td>
<td style="text-align:right;">
6.042196
</td>
<td style="text-align:right;">
5.947328
</td>
<td style="text-align:right;">
6.137065
</td>
</tr>
<tr>
<td style="text-align:right;">
48.0
</td>
<td style="text-align:right;">
5.09
</td>
<td style="text-align:right;">
5.891132
</td>
<td style="text-align:right;">
5.787013
</td>
<td style="text-align:right;">
5.995249
</td>
</tr>
<tr>
<td style="text-align:right;">
54.9
</td>
<td style="text-align:right;">
7.20
</td>
<td style="text-align:right;">
6.504277
</td>
<td style="text-align:right;">
6.433552
</td>
<td style="text-align:right;">
6.575002
</td>
</tr>
<tr>
<td style="text-align:right;">
52.7
</td>
<td style="text-align:right;">
6.66
</td>
<td style="text-align:right;">
6.308782
</td>
<td style="text-align:right;">
6.228823
</td>
<td style="text-align:right;">
6.388740
</td>
</tr>
</tbody>
</table>
</div>
<p>To plot this, you'd use a combination of <code>geom_line()</code> for the fitted values and <code>geom_ribbon()</code>, which would create the confidence interval region.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(simple_reg_plot_data) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">aes</span>(<span class="dt">x =</span> SVL) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Mass), <span class="dt">color =</span> <span class="st">&quot;cornflowerblue&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_ribbon</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> lwr, <span class="dt">ymax =</span> upr), 
              <span class="dt">fill =</span> <span class="kw">alpha</span>(<span class="st">&quot;black&quot;</span>, .<span class="dv">2</span>),  <span class="co"># dark fill with 80% transparency (alpha)</span>
              <span class="dt">color =</span> <span class="kw">grey</span>(.<span class="dv">4</span>), <span class="co"># dark-ish grey border line</span>
              <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st">   </span><span class="co"># dotted border line</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> fit))</code></pre></div>
<p><img src="Bio373L-Book_files/figure-html/a4_lm_plot_manual-1.png" width="672" /></p>
<p>You can also use <code>predict()</code> to calculate the respected value of your response variable given new predictor(s); this is useful for interpolation and extrapolation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Create a data frame with new predictors</span>
svl_predictors =<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">SVL =</span> <span class="kw">c</span>(<span class="dv">20</span>, <span class="dv">150</span>, <span class="dv">600</span>)) <span class="co"># New predictors</span>
mass_predictions &lt;-<span class="st"> </span><span class="kw">predict</span>(simple_reg, 
                           <span class="dt">newdata =</span> svl_predictors)  <span class="co"># The newdata argument is key here</span>
                                                      <span class="co"># If unspecified, it uses the original data</span>
svl_predictors <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Mass_estimate =</span> mass_predictions)
## # A tibble: 3 × 2
##     SVL Mass_estimate
##   &lt;dbl&gt;         &lt;dbl&gt;
## 1    20          3.40
## 2   150         15.0 
## 3   600         54.9</code></pre></div>
<p>For more information, see the help page <code>?predict.lm</code>.</p>
</div>
</div>
<div id="anova" class="section level3">
<h3><span class="header-section-number">D.3.2</span> ANOVA</h3>
<p>Analysis of variance (ANOVA) is a special case of linear model where all of the predictors are all categorical. However, ANOVAs are usually treated differently from regressions for historical reasons. In R, you fit an ANOVA in the same way as a regression (with the <code>lm()</code> command); however, it's common to use the <code>aov()</code> command on the <code>lm</code>'s output to reformat the results into a more traditional style. For the simple (one-way) ANOVA follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Fit the model wtih a regression</span>
simple_anova_lm &lt;-<span class="st"> </span><span class="kw">lm</span>(Diameter <span class="op">~</span><span class="st"> </span>Color_morph, <span class="dt">data =</span> lizards) 
<span class="co"># Reformat into traditional ANOVA style; this is usually done with a pipe as part of the previous step</span>
simple_anova &lt;-<span class="st"> </span><span class="kw">aov</span>(simple_anova_lm)

<span class="co"># Look at the ANOVA table</span>
simple_anova <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()
##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Color_morph   2  50586   25293   985.2 &lt;2e-16 ***
## Residuals   654  16790      26                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre></div>
<p>The ANOVA table gives us estimates of variation explained by the predictor and the residuals. Note how different the output is from the summary of a regression, even though the underlying math is the same:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(simple_anova_lm)
## 
## Call:
## lm(formula = Diameter ~ Color_morph, data = lizards)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.8837  -3.1176  -0.1176   3.1163  18.1163 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       32.8837     0.3456   95.16   &lt;2e-16 ***
## Color_morphBrown  -8.7661     0.4854  -18.06   &lt;2e-16 ***
## Color_morphGreen -21.4086     0.4854  -44.11   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.067 on 654 degrees of freedom
## Multiple R-squared:  0.7508, Adjusted R-squared:   0.75 
## F-statistic: 985.2 on 2 and 654 DF,  p-value: &lt; 2.2e-16</code></pre></div>
<p>Two quick notes about this:</p>
<ol style="list-style-type: decimal">
<li>While <span class="math inline">\(R^2\)</span> isn't included in the <code>aov()</code> summary, it can be calculated as the total sum of squares of your predictors (in this case, Color_morph) divided by the total sum of squares including the residual; For this example, we have <span class="math inline">\(5.0586239\times 10^{4} / (5.0586239\times 10^{4} + 1.6790147\times 10^{4}) = 0.7508007\)</span>.<br />
</li>
<li>The <code>aov()</code> table provides a line for each predicting factor and the residuals; the <code>lm()</code> summary includes estimates for the intercept and the specific levels of the factors (e.g., <code>Color_morphBrown</code>). These represent the <strong>dummy coded</strong> variables that R uses under the hood; you don't need to worry about this, but I've got an explanation for them below if you're interested.</li>
</ol>
<p><strong>Dummy coding</strong>: R converts an ANOVA into a (multiple) regression model by changing a categorical predictor with <span class="math inline">\(n\)</span> levels into <span class="math inline">\(n-1\)</span> predictor variables that can have values of 0 or 1. The first level of the factor doesn't get a dummy variable; its mean is represented by the regression's intercept. The other dummy coefficients represent the mean difference between the reference level and the level they represent. In our example, the reference category is Blue, so the regression's intercept is the mean Diameter for blue lizards. The average value for brown lizards would be the intercept plus the <code>Color_morphBrown</code> coefficient (and similarly for green). The <code>aov()</code> function reinterprets the dummy coded results as a traditionally categorical analysis.</p>
<div id="anova-means-confidence-intervals" class="section level4">
<h4><span class="header-section-number">D.3.2.1</span> ANOVA means &amp; confidence intervals</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make a data frame with just your predictors (distinct removes duplicates)</span>
color_levels &lt;-<span class="st"> </span>lizards <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(Color_morph)
color_levels
## # A tibble: 3 × 1
##   Color_morph
##   &lt;chr&gt;      
## 1 Green      
## 2 Brown      
## 3 Blue

simple_anova_means &lt;-<span class="st"> </span>
<span class="st">  </span><span class="co"># Calculate means &amp; 95% CI</span>
<span class="st">  </span><span class="kw">predict</span>(simple_anova, <span class="dt">newdata =</span> color_levels, 
                             <span class="dt">interval =</span> <span class="st">&quot;confidence&quot;</span>, <span class="dt">level =</span> <span class="fl">0.95</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># Convert to data frame</span>
<span class="st">    </span><span class="kw">bind_cols</span>(color_levels) <span class="co"># add the prediction data as more columns</span>
simple_anova_means
## # A tibble: 3 × 4
##     fit   lwr   upr Color_morph
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;      
## 1  11.5  10.8  12.1 Green      
## 2  24.1  23.4  24.8 Brown      
## 3  32.9  32.2  33.6 Blue</code></pre></div>
</div>
<div id="post-hoc-tests" class="section level4">
<h4><span class="header-section-number">D.3.2.2</span> Post-hoc tests</h4>
<p>In general, the ANOVA tests whether a factor (such as color morph) explains a significant amount of variation in the response. To test whether there are significant differences between specific levels of a factor, you need to run post-hoc tests on your ANOVA. A common post-hoc is Tukey's HSD (honest significant difference).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">simple_anova <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">TukeyHSD</span>()
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = simple_anova_lm)
## 
## $Color_morph
##                   diff        lwr        upr p adj
## Brown-Blue   -8.766074  -9.906219  -7.625929     0
## Green-Blue  -21.408608 -22.548753 -20.268463     0
## Green-Brown -12.642534 -13.774806 -11.510261     0</code></pre></div>
<p>You can use the <code>witch</code> argument to specify specific level comparisons, but by default it compares all of them.</p>
<p>A traditional way of summarizing post-hoc tests is to assign one or more letters to significantly different levels, where levels with different letters are significantly different from each other. For example, the letter grouping <code>c(&quot;A&quot;, &quot;AB&quot;, &quot;B&quot;, &quot;C&quot;)</code> would indicate that group 1 and group 3 are different from each other, but not from group 2; group 4 is different from everything. In the above example, everything is different, so we could assign the letters A through C.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># We&#39;ll store these in a data frame for later use</span>
anova_means_letters &lt;-<span class="st"> </span>simple_anova_means <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">arrange</span>(Color_morph) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># These will be plotted alphabetically, so we&#39;ll sort them that way to keep things easy</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">anova_labels =</span> <span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>))
anova_means_letters</code></pre></div>
<pre><code>## # A tibble: 3 × 5
##     fit   lwr   upr Color_morph anova_labels
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;       
## 1  32.9  32.2  33.6 Blue        A           
## 2  24.1  23.4  24.8 Brown       B           
## 3  11.5  10.8  12.1 Green       C</code></pre>
</div>
<div id="plotting-anovas" class="section level4">
<h4><span class="header-section-number">D.3.2.3</span> Plotting ANOVAs</h4>
<p>The basics of plotting ANOVA results was covered in the last part of Section @ref(ggp_discx_conty), but we'll refine them a bit here. The main additions are the use of <code>geom_text()</code> to include the labels above each category and <code>scale_y_continuous</code>, which we use to customize the y axis a bit so that it doesn't cut off the labels. Be sure to indicate in your figure captions what the letters mean.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggforce) <span class="co"># for geom_sina()</span>
<span class="co"># We&#39;re going to add post-hoc letters to this plot</span>
letter_y_position &lt;-<span class="st"> </span><span class="kw">max</span>(lizards<span class="op">$</span>Diameter) <span class="op">*</span><span class="st"> </span><span class="fl">1.05</span> <span class="co"># Put letters at the top</span>

anova_plot &lt;-<span class="st"> </span><span class="kw">ggplot</span>(lizards) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">aes</span>(<span class="dt">x =</span> Color_morph) <span class="op">+</span><span class="st"> </span><span class="co"># Color_morph column is in both lizards AND anova_means_letters</span>
<span class="st">  </span><span class="co"># Show the raw data</span>
<span class="st">  </span><span class="kw">geom_sina</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Diameter), <span class="co"># Diameter column is in lizards data frame</span>
            <span class="dt">color =</span> <span class="kw">alpha</span>(<span class="st">&quot;blue&quot;</span>, .<span class="dv">2</span>)) <span class="op">+</span><span class="st">  </span><span class="co"># semi-transparent points</span>
<span class="st">  </span><span class="kw">geom_errorbar</span>(
    <span class="kw">aes</span>(<span class="dt">ymin =</span> lwr, <span class="dt">ymax =</span> upr), <span class="co"># columns lwr and upr are in anova_means_letters</span>
    <span class="dt">data =</span> anova_means_letters,    <span class="co"># Use the summary data frame instead of lizards</span>
    <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, 
    <span class="dt">width =</span> .<span class="dv">3</span> <span class="co"># How wide the error bars are</span>
  ) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> fit), <span class="co"># fit column is in anova_means_letters</span>
             <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>,
             <span class="dt">data =</span> anova_means_letters) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> anova_labels), <span class="co"># label is the aesthetic used to indicate text</span>
            <span class="dt">y =</span> letter_y_position, <span class="co"># This is a fixed spot, not an aesthetic</span>
            <span class="dt">fontface =</span> <span class="st">&quot;bold&quot;</span>,
            <span class="dt">size =</span> <span class="dv">6</span>, <span class="co"># font size</span>
            <span class="dt">data =</span> anova_means_letters) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(
    <span class="co"># insure the letters aren&#39;t cut off at the top</span>
    <span class="dt">limits =</span> <span class="kw">c</span>(<span class="ot">NA</span>, letter_y_position), <span class="co"># This is the same as ylim()</span>
    <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">50</span>, <span class="dt">by =</span> <span class="dv">10</span>), <span class="co"># set axis ticks every 10 points</span>
    <span class="dt">name =</span> <span class="kw">c</span>(<span class="st">&quot;Perch Diameter (mm)&quot;</span>) <span class="co"># this is the same as ylab()</span>
  ) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Color Morph&quot;</span>)
anova_plot</code></pre></div>
<p><img src="Bio373L-Book_files/figure-html/a4_anova_plt_1-1.png" width="672" /></p>
</div>
</div>
<div id="comparing-two-means-t-tests" class="section level3">
<h3><span class="header-section-number">D.3.3</span> Comparing two means (t-tests)</h3>
<p>While it's perfectly valid to use an ANOVA to compare the means of two samples, the t-test is a more traditional approach. You can do this with the <code>t-test()</code> function.</p>
<p>First, let's create a 2-level categorical variable to work with. Normally, this would be done during data collection, but there aren't any in this data source. Let's define lizards as big (SVL &gt;= 65 mm) or small (SVL &lt;= 55 mm) and remove the intermediates.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lizards_by_size &lt;-<span class="st"> </span>lizards <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(SVL <span class="op">&lt;=</span><span class="st"> </span><span class="dv">55</span> <span class="op">|</span><span class="st"> </span>SVL <span class="op">&gt;=</span><span class="st"> </span><span class="dv">65</span>) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># Remove the lizards of intermediate size</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Size_class =</span> <span class="kw">if_else</span> (SVL <span class="op">&gt;=</span><span class="st"> </span><span class="dv">65</span>, <span class="st">&quot;big&quot;</span>, <span class="st">&quot;small&quot;</span>) )<span class="co"># Define Size_class as big or small, based on SVL</span></code></pre></div>
<p>Next, let's use a t-test to see if limb length differs between big and small lizards. First, we should look at the mean and standard deviation of each group. The classic t-test requires that the variances of the two groups are equal; if not, an adjustment will need to be applied. In practice, this adjustment has no ill effect if the variances are equal, so you may as well apply it. In any case, it's a good idea to look at data summaries before running a test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lizard_size_sumary_table &lt;-<span class="st"> </span>lizards_by_size <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Size_class) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># We want to summarize each size class</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(Limb), <span class="dt">sd =</span> <span class="kw">sd</span>(Limb), <span class="dt">var =</span> <span class="kw">var</span>(Limb), <span class="dt">n =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>()
lizard_size_sumary_table</code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   Size_class  mean    sd   var     n
##   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 big         15.1 0.984 0.969   240
## 2 small       11.2 0.800 0.641   206</code></pre>
<p>In this case, the standard deviations are somewhat different, but not particularly. In any case, we'll run the test without assuming for equal variances.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lizard_t_test &lt;-<span class="st">  </span><span class="kw">t.test</span>(Limb <span class="op">~</span><span class="st"> </span>Size_class, <span class="co"># formula specifies response (on left) and predictor (on right)</span>
                         <span class="dt">data =</span> lizards_by_size, 
                         <span class="dt">var.equal =</span> <span class="ot">FALSE</span>) <span class="co"># Assume unequal variances; this is the default option.</span>
<span class="kw">print</span>(lizard_t_test)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Limb by Size_class
## t = 45.668, df = 442.74, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  3.694599 4.026898
## sample estimates:
##   mean in group big mean in group small 
##            15.09958            11.23883</code></pre>
<p>When reporting a t-test, you should <em>t</em>, the degrees of freedom, the p-value, the effect size (Cohen's <em>d</em>). The effect size isnt' provided for you directly, so you'll need to calculate it yourself.</p>
<div id="effect-size-cohens-d" class="section level4">
<h4><span class="header-section-number">D.3.3.1</span> Effect size: Cohen's <em>d</em></h4>
<p>Cohen's <em>d</em> is essentially a standardized way of measuring the difference between two groups. Conceptually, it's the number of standard deviations of difference between the two groups. You can calculate it by taking the difference in the group means and dividing by the pooled standard deviation. To get the pooled standard deviation, calculate the weighted average of the variance (weighted by population size) and take the square root.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lizard_size_sumary_table <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_diff =</span> <span class="kw">diff</span>(mean),
            <span class="dt">pooled_variance =</span> <span class="kw">sum</span>(var <span class="op">*</span><span class="st"> </span>n) <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(n) ) <span class="op">%&gt;%</span><span class="st"> </span><span class="co">#weighted mean of variance</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">cohen_d =</span> <span class="kw">abs</span>(mean_diff) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(pooled_variance) ) <span class="co"># COhen&#39;s d is always positive, so take abs() of mean_diff </span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   mean_diff pooled_variance cohen_d
##       &lt;dbl&gt;           &lt;dbl&gt;   &lt;dbl&gt;
## 1     -3.86           0.817    4.27</code></pre>
<p>You could report your results as follows (assuming that figure 1 compared the two groups):</p>
<blockquote>
<p>Big lizards have significantly longer limbs than small lizards (d = 4.27, t = 45.7, df = 442.7, p &lt; 0.0001; Figure 1)</p>
</blockquote>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="dplyr-tutorial.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tidyr-tutorial.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
