# Preliminary Manuscripts {#prelim_ms}

The first stage of manuscript writing in Bio 373L is **preliminary manuscript**.  For this class, a preliminary manuscript is an important subset of a manuscript that will let me evaluate your writing and analysis before you spend the time to complete the whole manuscript.  

Preliminary manuscripts consist of:

  - Four Key Paragraphs
  - A brief list of analyses & their results
  - Your figures & tables
  - At least four references
  
The order of these three sections doesn't really matter

Preliminary manuscripts are due at the beginning of the next class period.

## Key Paragraphs

The four most important paragraphs of a paper are the first & last paragraphs of the introduction and discussion. I'm borrowing this explanation from a [great post](https://dynamicecology.wordpress.com/2016/02/24/the-5-pivotal-paragraphs-in-a-paper/) by Brian McGill, so I will just quote him:

> **First paragraph of the introduction** – you should use this paragraph to embed and contextualize your work in the context of a large classic, timeless, eternal question. What drives species richness. Or controls abundance or distribution. Or gives the best management outcome. Or explains why species are invasive. Or controls carbon flux. You of course are not going to fully answer this question. Indeed no one person, and probably even no generation of scientists will fully answer this question, but ask a really big question. You can then use this big question setup to spend the rest of the introduction summarizing past attempts to answer this question, and show how they have all failed to address the key issue you are about to address.

> **Last paragraph of the introduction** – This is probably the 2nd most important paragraph after the abstract. It MUST give a clear concise statement of what your core hypothesis, question or goal is. So while #1 is very general and you won’t/can’t answer it, #2 is totally specific to your paper and it should be answered before the paper is done (at least in your system). Depending on the field and your work, this may be phrased as a hypothesis, a question or a goal. But it should be crystal clear what your paper is about. Aside from readers getting really cranky if you haven’t clearly stated your question by the time they get to the end of the introduction, this is a great set up to start telling them how you answered it in the next section (methods). But do not start introducing (even in a summary fashion) the methods – here. This is a very common mistake I see. State the question independent of methods.

> **First paragraph of the discussion** – You have just taken the reader through the weeds of every analysis you have done, every comparison to a null model, every check on alternative models and buried them in p-values or AIC values (or preferably effect sizes, R2 and RMSE numbers). You now must pull up out of the weeds and tell them what the IMPORTANT results are, the ones you want them to remember. You probably told them 6 or 7 things, but some of those were necessary side shows. Take them back to the main attractions. (And if you want them to remember 5 different things you either haven’t thought it through enough or you need to split up your paper). This is also where you start shedding the statistical rigor you needed in the results section and pulling back to emphasizing the biological interpretation. This paragraph often looks as simple as one sentence each for: recap of biological result #1, recap biological result #2, recap biological result #3, and together these suggest X. Boom! the reader is now back in the big picture and you have set up the whole rest of the discussion where you can acknowledge limitations on why #1-#3 aren’t perfect for proving X but can argue that they’re pretty good, and you can put X back into the context of the literature again.

> **Last paragraph of the discussion** – This paragraph is the most variable (the other paragraphs really should be used for only exactly the one purpose I mentioned). But in my experience this paragraph ties your main claim (from #3) which responds to your goal/question (from #2) back to your eternal question (#1) and makes a novelty statement about how you have made progress towards improving our knowledge of the eternal question. In this way it serves as a nice summary of the whole paper.

All guidelines on writing style in Chapter \@ref(style) should be followed.

## List of Methods & Analyses

You should briefly list out your methods (you can use bullet points) and the associated statistical results.
This can be as formal or informal as you'd like.

The main point I'm interested in is the analyses you ran; you should make sure to state reason for the analysis (e.g., to compare sapling vs. canopy tree ratios in each habitat), the test you use, the statistical results (test statistics, p-values, etc), and the interpretation (e.g., no significant difference in ratios).
You should also cite your relevant figures.

## Figures and Tables

You should create figures & tables (with their associated captions) that you intend to include in the final report.
Please follow all guidelines in Chapter @\ref(figures).


## Citations/References

You will need to have at least two citations in paragraph 1 and two in paragraph 4 (with a total of four unique citations).
This number will be expanded for the final manuscripts.
Please make use of the literature threads on Canvas.