# (PART) Writing Lab Reports  {.unnumbered}

# The Structure of a Scientific Manuscript {#structure}

Most of the work in this class is ultimately in service of writing a manuscripts.
By the end of the semester, you will write full manuscripts for five group projects (the labs) and an independent project.
This is an iterative process, which we will generally break into preliminary and full manuscripts.
Expectations for both of them are below.  

## Full Manuscripts

The main goal of scientific writing is to effectively communicate complicated concepts. Scientific manuscripts tend to follow a traditional structure that is intended to help an experienced reader navigate these concepts. Each section should answer a question:

- **Abstract**: Why should I read this? 
- **Introduction**: Why did you do this?  
- **Methods**: What did you do, how did you do it, and what species/locations did yo use? 
- **Results**: What did you find?  
- **Discussion**: What does it mean and why does it matter?
- **Literature Cited**: Doesn't really answer a question, but this is where you list the citations you used. 

Greater detail is provided in the following sections.
The five paragraphs identified as "key" are particularly important and are also part of the preliminary manuscripts.

### Title

This isn't really a section, but your manuscripts need a title better than "Succession Lab Manuscript."
The title could be a question, a description, or a statement.  A few examples: 

> "How will succession drive changes in a Texas ecosystem?"

> "Red invasive fire ants reduce native species diversity."

> "Historical patterns of structural heterogeneity at Brackenridge Field Lab"

### Abstract (key)

The abstract is a one paragraph summary that functions as an advertisement/elevator pitch for the rest of the paper.
A biologist who reads your abstract should have a general idea about what you did, your most important results, and why that matters; ideally, it will be enough to make them interested in reading the rest of the paper. 
While this section should cover the intro, methods, results, and discussion, you **shouldn't re-use any of your writing from those sections here**. 
Instead, write a sentence or two from each that hits the important points without going into all of the details.
In particular, make sure you hit on all four of the other key paragraphs (described below).
Don’t cite any figures, tables, or other literature in here. 

If this is more than 400 words, it is too long.

`r # Add some examples here of good and bad abstracts.`

I generally prefer to write my abstract after the rest of the paper is done (or at least mostly done), so that I can summarize the rest of the work.
Other scientists like to start with the abstract and use it as an outline for the rest of their manuscript.

### Introduction

The introduction section sets the stage for the work you are about to describe and should tell your reader *why* your research is interesting. You should begin by describing the broader ecological context that your research fits into, and review the relevant literature. Start generally and narrow the focus to the specific project you did. 

The introduction should contain at least three paragraphs (with a minimum of four sentences each).
You should cite at least four peer-reviewed papers in this section.

#### First paragraph (key)

This paragraph introduces a broad ecological question that is relevant to your research.  
You will not be answering this question directly (a single paper couldn't possibly do this; instead, your manuscript will examine a *tiny* part of it).
Ultimately, you need to establish large-scale context so that the reader can understand how your work fits in with the broader context.
You should *not* mention your study site (e.g., BFL) or your specific questions here; in most cases, your specific study species should also be avoided. 

#### Last paragraph (key)

This is where you state and explain your goals, purpose, questions, and hypotheses.
While previous paragraphs are fairly general, this should be focused on what you tried to answer with your research.
This serves as a good buildup to the methods section (where you talk about *how* you answered your questions; don't do that here). 

You should talk about additional information that is relevant to understanding your question in this paragraph.
For example, if your question is about a somewhat abstract process (like succession), this is where you would want to link it to some more measurable proxy (like canopy to sapling ratios). Be careful, though; it can be very easy to start talking about material that belongs in the methods section.

#### Middle paragraphs

These bridge the first & last paragraphs and are often useful for narrowing the focus from general to specific.
This is a good place to review specific examples of your broad question from paragraph 1 and discuss limitations of previous research (particularly if your study will address those).

If your broader subject has been studied in your species or site before, a middle paragraph would be a good place to introduce/review that.
However, a general description of your study site or species is *not* appropriate for this section.
That belongs in the methods.

#### An example

Let's say you're writing a paper about the temperature tolerance of the three-eyed sandslider (*Trioptis cerastes*), a fictional snake species that is native to southwestern deserts.
A reasonable introduction could discuss the following:

- Climate change in general.
- Severity and effects of climate change in deserts.
- Effects of higher temperature on ectotherm behavior.
- Temperature tolerance in the three-eyed sandslider.

Alternatively, you could introduce the same paper in a completely different context:

- The evolution of animal activity budgets.
- Effects of temperature on foraging and reproductive behavior in ectotherms.
- Temperature tolerance in the three-eyed sandslider.

There are many more potential ways to write this paper.
The take home message is to set your specific project within the bigger picture of a large-scale concept, phenomenon, or issue. 


### Methods

This section includes detailed information on your experimental setup, data collection procedures, and the statistical analyses you used.
If your project focused on specific species or sites (e.g., BFL), you should start by describing these. 

It is often useful to organize the methods section into sub-sections. For example, for the temperature tolerance example could have the following sub-sections:

- Study Site
- Study Organism
- Experimental Design / Data Collection
- Statistical Analyses

You should always include a description of *all* of the statistical methods you used in the methods section.
This includes the test(s) performed, the predictor (independent) and response (dependent) variables, and the program used.
That being said, redundancy isn't necessary; if you did all of your analyses in R, you can simply state "All analyses were done in R v. 4.1.2." at the end of the paragraph.  

#### Study Site/Species

Sometimes, it can be tricky to figure out if background information on your study site/ species goes in your methods section or the introduction.
My suggestion: previous research on your study system that directly relates to your broader question should go in a middle paragraph of the introduction.
Anything else goes in the methods.
You can include sections in both.  

### Results

This is where you describe your observations and the results of any analyses.
Make sure you do not include new methods (**including new statistical analyses**) in this section; these belong in the previous section.

The most important results should be presented as figures or tables (see chapter \@ref(figures)). 
However, they must also be described in the paragraph. 
Related results should be presented together; for example, if you created figures that showed the relative proportion of species among age classes and also ran a Chi-squared test on species-by-age class counts, you should present them together in the same sentence.  

It can be a good idea to organize this section into sub-sections as well, if you had multiple different sets of analysis.

#### Reporting statistics

In general, you should begin by presenting the relevant summary statistics (such as means for measured data and  frequencies for categorical data). For example, ‘The mean temperature tolerance was $39.2 \pm 0.45 ºC$ for males and $37.1 \pm 0.25 ºC$ for females.’ Notice that the temperature has units (degrees Celsius) and that I put the standard deviation after the mean. This is good practice when reporting means. 

When reporting statistical test results, state what they mean in words first, and then follow the statement with a parenthetical phrase containing the statistics. For example, ‘Males tolerated significantly higher temperatures than females ($t = 1.96$, $df = 6$, $p = 0.04$)’. Notice that I included the computed t-statistic, the degrees of freedom and the p-value. All these should be reported when reporting t-test results. Note also that I indicated the direction of the difference, as well as its significance. 

Here is another example: ‘The number of escape behaviors performed increased significantly at high temperatures for all snakes ($\chi^2 = 8.43$, $df = 2$, $p = 0.001$; Figure 2)’. This is an example of how you would report chi-square test results. Again, the results are stated in words that have biological meaning and are followed by the calculated test statistic, the degrees of freedom and the p-value in parentheses. Note that I've also cited a relevant figure here.

If your statistical analyses did not find a significant difference, you still need to report this. For example: ‘Although temperature tolerance was slightly higher for males than females, this difference was not statistically significant ($t = 0.657$, $df = 6$, $p = 0.14$; Figure 3).’ Do not use the word “insignificant” in this context.

*Be sure to state your results in a biologically meaningful manner.*  A common mistake is to write out the results in statistical terminology without any reference to their biological meaning. For example: ‘A t-test resulted in a p-value of 0.03 meaning that we can reject the null hypothesis and accept the alternative.’ While this is a correct statistical interpretation of the calculated p-value, it tells the reader nothing about the trees or ants or mushrooms that you were studying. Do not write up your results like this; it's unpleasant to read and you're just going to have to fix it in revisions. 



#### Do not interpret your data here

Do not interpret your data in the results. That belongs in the discussion.

Do not consider explanations for your data in the results. That belongs in the discussion.

Do not consider how your data relates to your hypothesis in the results. That belongs in the discussion. 

This is probably the most common mistake I've encountered in grading student lab reports. 

### Discussion

The discussion is where you should interpret your data and draw conclusions by comparing your data to what is known from the published literature. The organization of this section is a mirror-image of the introduction in terms of its organization: start narrowly, by discussing how your results relate to your original hypotheses and questions. Follow it up with a wider discussion of how these results fit into the broad concept with which you introduced the paper. This should not be a restatement of what you wrote in the introduction or in the results, but should be an exploration of the meaning of all those numbers you just crunched and what they might signify. 

Be careful not to make unfounded statements. There are often many potential explanations for obtaining a particular result. One may seem more likely than the others, but this does not exclude the other explanations from being true if you haven't actually tested them. A good way to handle this is to mention the multiple alternative interpretations, express support for the one you think is most likely and explain why, then suggest a future experiment that could be done to test whether or not that is correct. 

#### First Paragraph (key)

Your result section will likely have a variety of different analyses presented in a technical manner, which may answer a variety of different questions.
This paragraph should tell the reader what the most *important* results were, as they relate to your specific questions/hypotheses from the end of the introduction.
Minor analyses, assumption checks, or other sideshows from the results can be ignored here.  
You should end the paragraph by talking about the biological implications/interpretations of the results, and how they relate back to your goals/hypotheses.

#### Last paragraph (key)

This one is the most challenging of the key paragraphs to write, and is a bit less prescribed.
Generally, this should connect your primary results back to the broad question from the beginning of the introduction.
Ideally, this would be a great place to make a novelty statement, where you discuss how your research has moved the field forward.
That can be difficult (particularly for the group projects, which have been done twice a year for the past 2 decades), so another good option is to talk about what new questions your research raises that are worth further investigation.  


#### Middle paragraphs

Between the first and last paragraphs is a good place to talk about your results in more detail, acknowledge limitations, and talk about how they relate to the literature.
In particular, this is a good place to talk about some of the side-results that you omitted in the first paragraph.
Consider multiple explanations, if you can.
These paragraphs are also a decent place to suggesting technical improvements for future research (but not new research directions).

An example:

> The lower temperature tolerance in females presents several possible explanations.
> Females are the smaller sex, meaning that they would heat up faster than males due to a greater surface area:volume ratio (Loblaw and Bluth, 2005). 
> Alternatively, it is possible that the males had higher tolerance because their overall activity levels were lower in the experimental enclosures, which could have given them lower initial internal temperatures that would take longer to reach critical levels.
> The amount of activity required to create a relevant temperature change would suggest that this is an unlikely option, however.
> Future work could address this by taking internal temperature readings before and after temperature tolerance trials.

### Literature

You must use a minimum of **six** primary literature sources in your report, with at least **four** sources in **both the introduction and discussion** (it's fine to have some overlap).  Use the sources to provide background, to aid in justification of performing the project, support for your interpretation of results, etc. In some cases, you should also cite a reference in the methods section (e.g., for a non-standard data collection technique or to provide information on a study site/species). Do not cite papers in results. All thoughts, ideas, concepts, etc., that you didn't think up on your own must be cited in the text (failure to do this is considered plagiarism). 

**Sources need to be relevant to your lab report at more than just a surface level.**
For example, if your lab report is on the distribution of cottonwoods at BFL, a paper about the cottonwood’s genomic structure is probably not going to be relevant.

Please note that while there is a minimum of six primary literature sources, you are encouraged to add more. Bringing in information from extra papers can really strengthen your introduction/discussion. There will be a weekly thread on Canvas to share literature relevant to the lab report; you are expected to contribute two citations to it each week.

Additional guidelines on using the literature are available in the [Writing Style Chapter](#style_lit).

## Preliminary Manuscripts

The first stage of manuscript writing in Bio 373L is **preliminary manuscript**.  For this class, a preliminary manuscript is an important subset of a manuscript that will let me evaluate your writing and analysis before you spend the time to complete the whole manuscript.  

Preliminary manuscripts consist of:

  - A good title
  - An abstract
  - The first & last paragraphs of the introduction
  - A brief list of analyses & their results
  - Your figures & tables
  - The first & last paragraphs of the discussion
  - At least four references

All guidelines on [writing content & style](#style) should be followed.

### The Five Paragraphs

The five most important paragraphs of a paper are the abstract and the first & last paragraphs of the introduction and discussion. These have been described in the full manuscript section; for a complementary view, read this [excellent blog post](https://dynamicecology.wordpress.com/2016/02/24/the-5-pivotal-paragraphs-in-a-paper/).

Submitting them as the first part of your manuscript gives me an opportunity to provide feedback faster and reduce the amount you'll need to change or revise if you are really off-base. 

### List of Methods & Analyses

You should briefly list out your methods (you can use bullet points) and the associated statistical results.
This can be as formal or informal as you'd like.

The main point I'm interested in is the analyses you ran; you should make sure to state reason for the analysis (e.g., to compare sapling vs. canopy tree ratios in each habitat), the test you use, the statistical results (test statistics, p-values, etc), and the interpretation (e.g., no significant difference in ratios).
You should also cite your relevant figures.

## Figures and Tables

You should create figures & tables (with their associated captions) that you intend to include in the final report.
Please follow all guidelines in Chapter @\ref(figures).

## Citations/References

You will need to have at least two citations in your intro and two in the discussion (with a total of four unique citations).
This number will be expanded to six for the final manuscripts.
Please make use of the literature threads on Canvas.

<!-- ## You don't need to write a manuscript in order -->

<!-- The order a manuscript is present in doesn't need to correspond with the order you write it. -->
<!-- I generally find it easiest to start with the last paragraph of the introduction (laying out my objectives/hypotheses), then write the methods & results, then the first paragraph of the discussion (which summarizes the biologically important details of the results), before fleshing out the rest of the intro and discussion. -->
<!-- I finish the abstract last. -->
<!-- Other scientists prefer to start with the abstract, as it helps them clarify the paper as a whole. -->
<!-- Ultimately, you'll need to figure out what approaches work well for you. -->



